"""
Django settings for PensiuneaSchilacy project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4s+!lpq@*z+13oouk9z!tj1=p3x(z4caf*&n5bzs*ckz^2x8a9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cazare',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PensiuneaSchilacy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PensiuneaSchilacy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'cazare.Utilizator'

# Setari pentru Login/Logout
LOGIN_REDIRECT_URL = 'acasa'   # Numele rutei pentru homepage
LOGOUT_REDIRECT_URL = 'login'  # Numele rutei pentru login
LOGIN_URL = 'login'            # Unde te trimite daca incerci sa intri undeva fara voie

# --- JAZZMIN SETTINGS ---
JAZZMIN_SETTINGS = {
    # Titlul care apare in tab-ul browserului
    "site_title": "Pensiunea Schilacy Admin",

    # Titlul de pe ecranul de login
    "site_header": "Pensiunea Schilacy",

    # Logo-ul text (daca nu ai poza)
    "site_brand": "Schilacy PMS",

    # Mesajul de bun venit de pe ecranul de login
    "welcome_sign": "Bine ați venit în panoul de administrare",

    # Copyright-ul de jos
    "copyright": "Pensiunea Schilacy Ltd",

    # Bara de cautare (Search) va cauta automat in Rezervari (foarte util!)
    "search_model": ["cazare.Rezervare"],

    # Meniul lateral (Customizam ordinea iconitelor)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "cazare.Utilizator": "fas fa-user-shield",
        "cazare.Rezervare": "fas fa-calendar-check",
        "cazare.Camera": "fas fa-bed",
        "cazare.TipCamera": "fas fa-layer-group",
        "cazare.Client": "fas fa-address-book",
        "cazare.Factura": "fas fa-file-invoice-dollar",
        "cazare.Problema": "fas fa-tools",
    },
    
    # Ordinea in meniu
    "order_with_respect_to": ["cazare.Rezervare", "cazare.Camera", "cazare.Client", "cazare.Factura"],
}

# --- JAZZMIN UI TWEAKS (Culori) ---
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # Poti incerca si: 'darkly', 'journal', 'simplex', 'slate'
    # "dark_mode_theme": "darkly", # Activeaza asta daca vrei mod intunecat automat
}